version: "3.9"

#befor assign the network docker , create first.
networks:
    frontend:
        external: true
    backend:
        external: true

services:
    cloudflaretunnel:
        container_name: cloudflaretunnel
        image: cloudflare/cloudflared:2023.8.2
        restart: unless-stopped
        environment:
            - TUNNEL_TOKEN=$TUNNEL_TOKEN
        command: tunnel --no-autoupdate run
        networks:
            - frontend
            - backend
## After place in the docker-compose file , export TUNNNEL_TOKEN={ your cloudflare tunnel token }
