http:
    middlewares:
        bouncer-traefik:
            forwardauth:
                address: http://bouncer-traefik:8080/api/v1/forwardAuth
                trustForwardHeader: true

        default:
            chain:
                middlewares:
                    - default-security-headers
                    - gzip

        secHeaders:
            chain:
                middlewares:
                    - default-security-headers
                    - gzip

        default-security-headers:
            headers:
                browserXssFilter: true
                contentTypeNosniff: true
                frameDeny: true
                sslRedirect: true
                #HSTS Configuration
                forceSTSHeader: true
                stsIncludeSubdomains: true
                stsPreload: true
                stsSeconds: 31536000
                customFrameOptionsValue: "SAMEORIGIN"
                customRequestHeaders:
                    X-Forwarded-Proto: "https"
        gzip:
            compress: {}
