version: "3"
services:
    code-server:
        image: lscr.io/linuxserver/code-server:latest
        container_name: code-server
        security_opt:
            - no-new-privileges:true
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/BST
            - PASSWORD=#####
            - SUDO_PASSWORD=#####
            # - PROXY_DOMAIN=code-server.jimsgarage.co.uk #optional
            - DEFAULT_WORKSPACE=/config/workspace #optional
        volumes:
            - /home/abid_home_server/coding-remote:/config:rw
        networks:
            backend:
        ports:
            - 8443:8443
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.code-server.entrypoints=http"
            - "traefik.http.services.code-server.loadbalancer.server.port=8443"
            - "traefik.docker.network=backend"
        restart: unless-stopped

networks:
    backend:
        external: true
