version: "3.8"

services:
    localstack:
        container_name: "${LOCALSTACK_DOCKER_NAME-localstack-main}"
        image: localstack/localstack:latest
        ports:
            - 4566:4566 # LocalStack Gateway
            - 4510-4559:4510-4559 # external services port range
        environment:
            - PUID=1000
            - PGID=1000
            - DEBUG=${DEBUG-}
            - DOCKER_HOST=unix:///var/run/docker.sock
        volumes:
            - "./volume:/var/lib/localstack:rw"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
